    1. MIN MAX SCALAR
    
    X_std = (X-X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    X_scaled = X_std * (max - min) + min

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
minmax= preprocessing.MinMaxScaler(feature_range=(5,9))
minmax.fit(x).transform(x)

C:\Users\rpark.CVC\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 5.,  5.,  5.],
       [ 7.,  7.,  7.],
       [ 9.,  9.,  9.]])

# First Feature - MinMax
min = 1
max = 7

x_std_0 = (1-1)/(7-1) = 0
x_std_4 = (4-1)/(7-1) = 3/6 = 0.5
x_std_7 = (7-1)/(7-1) = 6/6 = 1


# Standard Scalar
    
    0 mean, Unit Variance Standard Scaler
    (x-mean) / xstd

In [11]:
standard = preprocessing.StandardScaler().fit(x)
standard.transform(x)

C:\Users\rpark.CVC\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [13]:
x_st_0 = (1-4)/np.std(x[:,0])
x_st_0

-1.2247448713915892

# Binarize - Transforming data into 1 or zero given a threshold

In [14]:
preprocessing.Binarizer(5).fit(x).transform(x)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1]])

# Normalize
    
    each row / norm(row)

In [15]:
preprocessing.Normalizer().fit(x).transform(x)

array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231,  0.56980288,  0.68376346],
       [ 0.50257071,  0.57436653,  0.64616234]])

In [17]:
import math
x0 = 1
norm0 = math.sqrt(1+4+9)
x0/norm0

0.2672612419124244

In [19]:
import math
x0 = 4
norm0 = math.sqrt(16+25+36)
x0/norm0

0.4558423058385518