NumPy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
np.linspace(1,10,10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [14]:
#Identity Matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [15]:
np.random.rand(5)

array([ 0.29755618,  0.38132346,  0.10901951,  0.06615441,  0.83488619])

In [16]:
np.random.rand(5,5)

array([[ 0.42214727,  0.61738695,  0.94449893,  0.44781355,  0.40220908],
       [ 0.51993869,  0.92389266,  0.41253549,  0.65068553,  0.25522907],
       [ 0.66914826,  0.50879925,  0.22083019,  0.35832907,  0.52531294],
       [ 0.97636379,  0.98398526,  0.9945661 ,  0.64008776,  0.91601716],
       [ 0.63449576,  0.57067222,  0.34463512,  0.59718743,  0.28018897]])

In [17]:
#normal distribution
np.random.randn(2)

array([-1.70879545,  0.29940163])

In [18]:
#normal distribution
np.random.randn(2,2)

array([[-1.0186583 ,  0.56145783],
       [ 0.74849905,  0.24576173]])

In [20]:
#random integer from a low to a high number

np.random.randint(1,101,10)

array([96, 32,  7, 21,  4, 26, 18, 82, 32, 74])

In [3]:
# attributes and methods of an array

arr = np.arange(25)


In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
ranarr = np.random.randint(0,51,10)

In [7]:
ranarr

array([21, 32,  8, 42, 49,  9, 26, 45, 18,  5])

In [23]:
#the reshape method on an array - the number of elements must be the same
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
#find max or min values and their index location

ranarr

array([49, 36, 45, 38, 23, 30,  7,  4, 31, 38])

In [25]:
ranarr.max()

49

In [26]:
ranarr.min()

4

In [27]:
#index location of the value
ranarr.argmax()

0

In [28]:
#index location of the value
ranarr.argmin()

7

In [29]:
#what is the shape of the vector?
arr.shape

(25,)

In [31]:
arr=arr.reshape(5,5)

In [32]:
arr.shape

(5, 5)

In [33]:
#datatype
arr.dtype

dtype('int32')

## NumPy - Indexing and Selection

In [9]:
array1 = np.arange(0,11)

In [10]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array1[0]

0

In [12]:
array1[1]

1

In [13]:
array1[1:5]

array([1, 2, 3, 4])

In [14]:
array1[-1]

10

In [15]:
array1[-2]

9

In [19]:
array1[-1:0]

array([], dtype=int32)

In [25]:
array1[:6]

array([0, 1, 2, 3, 4, 5])

In [26]:
array1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
# broadcasting - assigns the value to the first 5 elements 

array1[0:5] = 100

In [29]:
array1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [30]:
slice_of_array1 = array1[0:6]

In [31]:
slice_of_array1

array([100, 100, 100, 100, 100,   5])

In [32]:
array1Copy = array1.copy()

In [33]:
array1Copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
#Indexing a 2D array

In [36]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[0][0]

5

In [39]:
arr_2d[2][1]

40

In [40]:
arr_2d[2,1]

40

In [41]:
#Grab certain section or sub matrix
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [42]:
arr_2d[2:2]

array([], shape=(0, 3), dtype=int32)

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
#up to but NOT including
arr_2d[1:2]

array([[20, 25, 30]])

In [46]:
arr_2d[2:]

array([[35, 40, 45]])

In [48]:
arr_2d.sum()

225

In [49]:
arr_2d[2:].sum()

120

In [50]:
arr = np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
bool_Array = arr > 5

In [54]:
#Only get the results where the boolean is true

arr[bool_Array]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr<5]

array([1, 2, 3, 4])

In [74]:
array2 = np.arange(100).reshape(10,10)

In [81]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
array2[4,0]

40

In [84]:
array2[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [85]:
array2[5:6,3:5]

array([[53, 54]])

# NumPy Operations

In [8]:
arr = np.arange(140,144)

In [9]:
arr

array([140, 141, 142, 143])

In [10]:
np.sqrt(arr[3])

11.958260743101398

In [11]:
arr + arr

array([280, 282, 284, 286])

In [12]:
arr - arr

array([0, 0, 0, 0])

In [93]:
#scalar means single number
# works for division, subtraction, multiplication, exponents

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [101]:
# Universal Array Functions
np.sqrt(144)


12.0

In [95]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [96]:
np.max(arr)

10

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [98]:
np.log(arr)

C:\Users\rpark.CVC\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [107]:
#NumPy Exercises Overview

In [111]:
import numpy as np

In [112]:
arr1= np.arange(0,5)

In [113]:
arr1

array([0, 1, 2, 3, 4])

In [114]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [115]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [117]:
np.zeros(10) + 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])